"""
Одноразовая миграция: загружает исторические данные поставщиков в БД.
Запускается при старте run_all.py если таблица пустая.
"""

import sqlite3
import os

_DATA_DIR = "/data" if os.path.isdir("/data") else "."
DB_PATH = os.path.join(_DATA_DIR, "suppliers.db")

HISTORICAL_DATA = [
    {"id": 1, "company": "Zhejiang Wenxin Mechanical & Electrical Co., Ltd.", "contact_name": "Ellen Yang (杨含笑)", "phone": "+86-152-1475-8900", "email": "ellen@wenxinmfg.com", "website": "www.wenxinmfg.com", "products": "Plant protection UAV (drones): G10, G20, G30; X1800 Power Line Drone; agricultural sprayers", "country": "China", "city": "Taizhou, Zhejiang Province", "voice_comment": "Sales Manager Ellen met at trade exhibition, company is integration factory and trade, also has website www.power-sprayer.com", "created_at": "2026-04-17T00:39:09.405372"},
    {"id": 2, "company": "EncoSmart Technology (享刻智能)", "contact_name": "Yafei Ji (纪亚飞)", "phone": "+86 13911040006", "email": "jiyafei@encosmart.com", "website": "www.encosmart.com", "products": "Robotic arms, smart automation equipment, cobot solutions", "country": "China", "city": "Beijing", "voice_comment": "COO at EncoSmart Technology, also holds General Manager role at 九号商用(北京)科技有限公司 with website www.segwayrobotics.com. Office at 301 3rd Floor Zhongguancun AI Innovation Base No.17 Zhichun Road Haidian District Beijing", "created_at": "2026-04-17T00:40:18.622539"},
    {"id": 3, "company": "Zhejiang Safun Industrial Co., Ltd", "contact_name": "Annie (胡颖婷)", "phone": "+86-579-89281712", "email": "Annie@safuntool.com", "website": "www.safuntool.com", "products": "Robotic lawn mowers (TrueGreen Fine Fox-S series, model TG8B170 Fine Fox-S6): cutting area 5000m2, cutting width 220mm, cutting height 25-60mm, no boundary wire, mowing time 140 min per charge, max slope 20 degrees, AI vision, GPS+RTN, intelligent obstacle avoidance, rain sensor, multi-zone management", "country": "China", "city": "Yongkang, Zhejiang", "voice_comment": "", "created_at": "2026-04-17T00:41:14.538553"},
    {"id": 4, "company": "RoboCT Group", "contact_name": "Yellow (黄崇徒)", "phone": "+86 157 5712 4856", "email": "yellow@ascentizexo.com", "website": "www.RoboCT.com", "products": "GoGo-H Exoskeleton (нижние конечности), Power-Assisted Exoskeleton для промышленности (верхние конечности, пояс)", "country": "China", "city": "Hangzhou", "voice_comment": "Экзоскелеты для промышленного применения и реабилитации. GoGo-H: +34% силы ног, -30% ЧСС, -40% износа коленных суставов. Промышленная линейка: снижение нагрузки до 50%, помощь до 25 кг, вес от 4 кг.", "created_at": "2026-04-17T00:41:54.438438"},
    {"id": 5, "company": "Hangzhou Yile Shangyun Robot Technology Co.,Ltd", "contact_name": "Mark Hu (胡志涛)", "phone": "+86 18069759025", "email": "sales@ylvending.com", "website": "www.ylvending.com", "products": "Smart vending machines, coffee machines, robotic kiosks", "country": "China", "city": "Hangzhou", "voice_comment": "COO Mark Hu, also known as 胡志涛 (Executive General Manager). Company is a China National Standard-setter in the Coffee Machine Industry. Address: NO.100 Changda Road, Hangzhou Linping Economic Development Zone, Linping District, Hangzhou, China. Additional phone: +86 13777805202", "created_at": "2026-04-17T00:42:46.014667"},
    {"id": 6, "company": "Zhejiang YAT Electrical Appliance Co., Ltd.", "contact_name": "Dwan Wu", "phone": "+86 188 6866 4321", "email": "dwan.wu@yat.com", "website": "", "products": "Robotic Lawn Mowers (RTK+Vision 22.5cm, LiDAR+Vision 18cm, VSLAM 18cm)", "country": "China", "city": "Jiaxing, Zhejiang", "voice_comment": "Senior Sales Manager Third Division. Products feature AI vision obstacle avoidance, LiDAR+Vision fusion, RTK+Single camera vision, Visual SLAM navigation. Recommended areas up to 4000m2.", "created_at": "2026-04-17T00:43:45.853622"},
    {"id": 7, "company": "北京爱宾果科技有限公司 (Beijing AiBingo Technology Co., Ltd.)", "contact_name": "李明良", "phone": "400-6250-073", "email": "lml@hi-bingo.com", "website": "www.aibingo.com", "products": "Bingo AiLight - AI智慧光辅导设备，全球首款无屏化AI辅导设备，AR+AI多感官学习，智慧光投影交互学习台灯", "country": "中国", "city": "北京", "voice_comment": "清华大学X-lab孵化项目，荣获日内瓦国际发明展金奖，产品面向K12全学段，支持作业批改、AR投影、纸与光交互", "created_at": "2026-04-17T00:45:24.879108"},
    {"id": 8, "company": "Suzhou Alpha Robotics Co., Ltd", "contact_name": "Nick Xu, Minnie Ray", "phone": "+86 181 3606 0913, +86 181 1555 1873, +86 512-57476881", "email": "xuhao@alpharobotics.ai, shimin@alpharobotics.ai", "website": "www.alpharobotics.ai", "products": "Last-mile delivery robots, reception robots, Speedybot Max indoor and outdoor delivery robot", "country": "China", "city": "Suzhou", "voice_comment": "Leading brand of last-mile and reception robots, sold in over 90 countries worldwide. Offices in Suzhou CN, Tokyo JP, Pennsylvania US.", "created_at": "2026-04-17T00:46:43.849154"},
    {"id": 9, "company": "Sublue Underwater AI Co.,Ltd", "contact_name": "Debbie Feng", "phone": "+86 13836889037", "email": "kaijia.feng@sublue.com", "website": "www.sublue.com", "products": "Underwater scooters: Sublue Mix 2026, Sublue MixPro 2026, Sublue Navbow, Sublue Navbow+, Sublue Vapor, Sublue Vapor Pro", "country": "China", "city": "Tianjin", "voice_comment": "Sales Manager Debbie Feng. Product line includes 6 underwater scooter models ranging from 690 to 4799 EUR. Distributor in Europe: CreateXtreme. 150000+ cumulative sales.", "created_at": "2026-04-17T00:47:44.824336"},
    {"id": 10, "company": "IIMT Robot (Jiangsu Jitri Intelligent Manufacturing Technology Institute Co.)", "contact_name": "Imane Zaroual, Steven Pan, Li Yujian", "phone": "+86 182 0509 2089, +86 185 5182 1908, 183 0601 3870", "email": "ImaneZar@iimt.org.cn, panjianjia@iimt.org.cn, liyujian@iimt.org.cn", "website": "www.iimtcobot.com, www.iimt.org.cn", "products": "Collaborative robots, autonomous mobile robots, intelligent cleaning robots (IIMT-CL-V), delivery robots (IIMT-DR-01, IIMT-DR-02), portable welding robots, intelligent coffee robots", "country": "China", "city": "Nanjing, Jiangsu Province", "voice_comment": "Imane Zaroual is Sales Manager and Digital Marketing Consultant. Steven Pan is International Sales. Li Yujian is Embodied Intelligence Lab Solutions Product Manager. Company is an intelligent robot manufacturer and system solution integrator founded in 2016, with CE and KCs certifications.", "created_at": "2026-04-17T00:48:54.981018"},
    {"id": 11, "company": "Rotunbot (Hangzhou) Technology Co., Ltd.", "contact_name": "Duan Tianye", "phone": "138-5185-2345", "email": "lvan@rotunbot.com", "website": "rotunbot.com", "products": "Rotunbot spherical robots for security, airport perimeter defense, bird control, adversarial operational scenarios", "country": "China", "city": "Hangzhou", "voice_comment": "Deputy General Manager, Sales and Channel Cooperation. Address: 1A01, 1st Floor, Building 8, No. 339, 25th Avenue, Baiyang Street, Qiantang District, Hangzhou, Zhejiang Province. Slogan: We make science fiction real.", "created_at": "2026-04-17T00:49:56.414773"},
    {"id": 12, "company": "Lingdu Intel-tech Development Co., Ltd. (X-Human / 凌度智能)", "contact_name": "Mia Lee, Helen (Zhou Lang), AdamChan", "phone": "+86-400-833-7577", "email": "mia@gd-ldznkj.com, helen@gd-ldznkj.com, adam@gd-ldznkj.com", "website": "www.x-humanbot.com", "products": "Curtain wall cleaning robots: Lingkong K3 (single curtain wall cleaning robot), Lingyun Y3 (Obstacle-Crossing Curtain Wall CleanBot)", "country": "China", "city": "Guangzhou", "voice_comment": "Компания производит роботов для мойки фасадов и витражных стен. Два основных продукта: Lingkong K3 — одиночный робот для плоских стеклянных фасадов, и Lingyun Y3 — робот с функцией преодоления препятствий. Контакты: Mia Lee (Overseas Sales), Helen и AdamChan (Sales Managers). Офис в районе Хуанпу, Гуанчжоу.", "created_at": "2026-04-17T00:51:23.538445"},
    {"id": 13, "company": "Shenzhen Kim Dai Intelligence Innovation Technology Co., Ltd", "contact_name": "Rain Chen", "phone": "+86 13827439695", "email": "rain.chen@kimdaipm.com", "website": "www.kimdaipm.com / www.kimdaiai.com", "products": "AI plush toys, smart pet companion robots, water fountains, pet hair care machines, pet brushes, Obexx smart virtual robots, OEM/ODM manufacturing", "country": "China", "city": "Shenzhen", "voice_comment": "Senior Account Manager. Factory offers R&D, mold manufacturing, injection molding, electronics assembly, SMT/PCBA. Certifications: ISO9001/14001/13485, IATF16949.", "created_at": "2026-04-17T00:53:07.616134"},
    {"id": 14, "company": "Shanghai Hi-Dolphin Robot Technology Co., Ltd. (上海氦豚机器人科技有限公司)", "contact_name": "韩非子 (Philip Han)", "phone": "+86 159 2163 8457", "email": "Philip.han@hi-dolphin.com", "website": "", "products": "COFE+ Fully Autonomous Multi-Beverage Latte Art Robot Cafe (机器人现磨咖啡), 7th Generation Robot Coffee Kiosk", "country": "China", "city": "Shanghai", "voice_comment": "Founder of Shanghai Hi-Dolphin Robot Technology. Product is COFE+ robot cafe system, 7th gen global debut. 110+ patents, exported to 65+ countries, 1000+ global landmark locations. Awards include European Product Design Award, Top 30 AI Robot Benchmark Enterprises. Recruitment hotline: 400 901 9691", "created_at": "2026-04-17T00:53:55.874813"},
    {"id": 15, "company": "Jiangsu Fenghai New Energy Seawater Desalination Development Co., Ltd.", "contact_name": "Jennver Yan (闫文星), Mr. Zhang Haoyu (Jasper)", "phone": "+86 13031409425, +86 19850635299, 0515-83558029", "email": "yanwenxing2035@163.com, zhanghaoyu@fhned.com, desalination@fhned.com", "website": "www.fhned.com, en.fhned.com, www.rewatertech.com", "products": "Seawater desalination, brackish water desalination, surface water purification, sewage treatment, new energy micro-grid, skid-mounted seawater desalination equipment (5 m3/d manual model FHNED-SWRO-5)", "country": "China", "city": "Yancheng (Dafeng District), Jiangsu Province", "voice_comment": "Two business managers from Desalination Department: Jennver Yan and Jasper Zhang. Company specializes in new energy-powered desalination solutions for islands, construction sites, oil platforms, hotels, military and agricultural use.", "created_at": "2026-04-17T00:54:59.137769"},
    {"id": 16, "company": "Gweike Tech Co., Ltd.", "contact_name": "Antonio Wang", "phone": "+86 155 5020 0074", "email": "antonio@wklaser.com", "website": "https://www.gweikecnc.com", "products": "Fiber Laser Engraving Machines (G2 20W/30W/50W), Fiber+CO2 Laser Cutting Machines (M2, M2 PRO, M2 MAX, M2 ULTRA, M3, M3 PRO, M3 MAX, M3 ULTRA), Fiber Laser Welding Machines (M800, M1200)", "country": "China", "city": "Jinan, Shandong", "voice_comment": "Met at Canton Fair, sales manager Antonio Wang, showed G2 small business fiber laser engraver demo with photo engraving on metal card, Canton Fair special prices available", "created_at": "2026-04-17T00:56:11.428540"},
    {"id": 17, "company": "Jiangsu Ebil Intelligent Storage Technology Co., Ltd", "contact_name": "Sunny Wang (汪萱)", "phone": "+86-158-5183-9288", "email": "sunnywang@ebilmetal.com", "website": "www.ebiltech.com", "products": "High-density intelligent storage solutions, teardrop pallet racking, AS/RS systems, shuttle racking, WMS software, conveyor systems", "country": "China", "city": "Nanjing", "voice_comment": "Ebil Tech - китайский производитель систем высокоплотного хранения. Контакт - Sunny Wang. Офис в Нанкине, завод в районе Гаочунь. Производят стеллажные системы включая американский тип teardrop, автоматизированные склады.", "created_at": "2026-04-17T00:57:05.174766"},
    {"id": 18, "company": "Shaoxing Nante Crane Equipment Co., Ltd.", "contact_name": "Brandon Ban, Daisy Du", "phone": "+86 137 5850 4534, +86 137 7736 5864", "email": "brandon.ban@nantecrane.com, daisy.du@nantecrane.com", "website": "www.nantecrane.com", "products": "Davit Crane, Rubber Tyre Gantry Crane, Jib Crane, Double Girder Box Type Gantry Crane, Launching Crane, Double Girder Truss Type Gantry Crane, Low Headroom Overhead Crane, Electric Hoists", "country": "China", "city": "Shaoxing", "voice_comment": "Компания представлена на выставке, стенд 20.1 A22-23 B01-02. Позиционируют себя как глобальный бренд энергосберегающего и интеллектуального подъёмного оборудования. Работают в 20+ отраслях, охватывают 50+ стран, 150+ партнёров, 5000+ конечных пользователей.", "created_at": "2026-04-17T00:57:59.181481"},
    {"id": 19, "company": "Anhui Koyo Rego Machinery Technology Co., Ltd", "contact_name": "Joy Daw / 黄艳", "phone": "+8618656159960", "email": "joydaw@ahrego.com", "website": "www.ahrego.com", "products": "Water purification equipment, Pure water bottling and packaging machines, Juice beverage production and packaging, Liquid packing machines, Granule and powder products packaging, Shrink wrapping machines, Filling machines", "country": "China", "city": "Hefei, Anhui", "voice_comment": "Manufacturer and exporter of complete filling and packaging systems. Over 3000 sets exported annually to 100+ countries. Certified by SGS and CAS.", "created_at": "2026-04-17T00:58:59.749391"},
    {"id": 20, "company": "深圳市好盈科技股份有限公司 (Shenzhen Hobbywing Technology Co., Ltd.)", "contact_name": "张裕彬 (Zhang Yubin)", "phone": "+86-13715310566", "email": "zhangyubin@hobbywing.com", "website": "https://www.hobbywing.com", "products": "UAV/Drone Power Systems, FPV Motors (2807, 2812, 3110, 4218, 4315, 4320), Drone Propellers (MFP Series), ESC (ESC-100A-4in1), Electric Motorcycle Motors (M16/MG16/M13/MG13 Series)", "country": "China", "city": "Shenzhen", "voice_comment": "Sales Manager at Hobbywing, exhibiting UAV/drone power systems and FPV motors at trade show. Also produces electric motorcycle motors up to 11kW. Contact via WeChat available.", "created_at": "2026-04-17T00:59:53.439089"},
    {"id": 21, "company": "xTool (XTL US INC.)", "contact_name": "Vanessa Tse", "phone": "+86 189 6636 8815", "email": "Vanessa@xTool.com", "website": "xtool.com", "products": "xTool F2 Ultra - dual laser engraver and cutter (60W MOPA + 40W Diode), laser engraving and cutting machine for metal, wood, leather, acrylic, paper", "country": "China", "city": "Shenzhen", "voice_comment": "Представитель Vanessa Tse, Channel Development Executive. Продукт xTool F2 Ultra - мощный двойной лазерный гравер с ИИ, скорость до 15000 мм/с, рабочая зона 220x220 мм или 220x500 мм с конвейером, двойные камеры 48МП, точность 0.2 мм", "created_at": "2026-04-17T01:00:52.986906"},
    {"id": 22, "company": "武汉华工激光工程有限责任公司 (Wuhan HGTech Laser Engineering Co., Ltd.)", "contact_name": "李阳 (Li Yang)", "phone": "15527899217", "email": "ahmed@hglaser.com", "website": "www.hglaser.com", "products": "Laser cutting machines, laser welding machines (Smart HWA air cooling handheld, Smart HW robot arm, Smart HW classic handheld), laser cleaning machines (Smart HC continuous handheld, Smart HP pulse handheld, Smart HPA portable compact)", "country": "China", "city": "Wuhan", "voice_comment": "International Sales Manager. Company listed on stock exchange with code 000988. Hotline: 400-888-8866. Address: No.66 Weilai 2nd Road, East Lake New Technology Development Zone, Wuhan, Hubei Province, HGTech Smart Manufacturing Industrial Park.", "created_at": "2026-04-17T01:02:16.853167"},
    {"id": 23, "company": "金科机械 Jinke Machinery", "contact_name": "Lucas Lin", "phone": "+86-13339103919", "email": "support@jinke-machinery.cn", "website": "www.tortilla-machine.com", "products": "Tortilla making machines, dough dividing and rounding equipment", "country": "China", "city": "Hefei", "voice_comment": "Lucas Lin is International Trade Manager at Jinke Machinery, located at Building C81, Jiahai Industry Park, Hefei City, Anhui Province, China. Company specializes in tortilla and flatbread production machinery.", "created_at": "2026-04-17T01:03:31.467295"},
    {"id": 24, "company": "Linyi Wante Machinery Co., Ltd.", "contact_name": "Cindy Gao", "phone": "+86 17853995669", "email": "blockmachine5@wtmachine.cn", "website": "http://www.wantegroup.com", "products": "Concrete Block Making Machine, Clay Interlocking Brick Machine, Block Palletizing Cuber Machine, GMT Glassfiber Pallet, Batching Plant", "country": "China", "city": "Linyi", "voice_comment": "General Manager Cindy Gao. Address: Rm 1205, Shangcheng INT, Linyi City, China. Models available: QT18-15, QT15-15, QT12-15, QT10-15, QT8-15, QT6-15. Company founded 2012, 1500 employees, 50 engineers, 50+ machine models.", "created_at": "2026-04-17T01:04:30.576433"},
    {"id": 25, "company": "QGM | ZENITH", "contact_name": "Peter Wang", "phone": "+62 81 3181 3573", "email": "peter@qzmachine.com", "website": "en.qzmachine.com | www.zenith.de", "products": "Block and paver making machines (QT10, Zenith 913 The Traveller, VP1500), hollow blocks, solid blocks, paving stones, curb stones, molds", "country": "Indonesia", "city": "Kabupaten Tangerang, Banten", "voice_comment": "Sales Manager for Southeast Asia. Office at Ruko Ice Business Park, BSD City, Blok C07. WhatsApp: +86 181 0595 6807. Zenith 913 price noted as 130,000 GBP (handwritten). QT10 capacity: 10,000-12,000 pcs hollow blocks per 8 hours.", "created_at": "2026-04-17T01:05:13.753646"},
    {"id": 26, "company": "Fujian Qunfeng Machinery Co., Ltd.", "contact_name": "Vivian Xu / Михаил Николаевич Безгрешнов", "phone": "+86-137 8882 7766 / +7(906)532 65 13", "email": "trade08@qunfeng.com / m.bezgreshnov@qunfeng.ru", "website": "www.qunfenggroup.com", "products": "Block machines, concrete product forming machines, vibropress equipment, intelligent block making solutions", "country": "China / Russia", "city": "Nanan, Quanzhou, Fujian / Тула", "voice_comment": "Компания представлена на выставке. Два контакта: Vivian Xu — региональный менеджер по продажам (Китай), Михаил Безгрешнов — руководитель сервисной службы (Россия, Тула). Продукция: вибропрессовое оборудование для производства бетонных блоков, третье поколение патентованного сервовибратора.", "created_at": "2026-04-17T01:05:57.672672"},
    {"id": 27, "company": "ThoYu", "contact_name": "Sophia Sun (孙淑静), Nancy Wang (王平平)", "phone": "+86 185 2159 0671, +86 152 3839 8301", "email": "sophia@palletmach.com, nancy@thoyu.com", "website": "www.thoyu.com", "products": "Pallet production equipment: plant fibre molded pallet production lines, hydraulic press machines for wood chip fiber molding pallets, one-stop pallet production solutions", "country": "China", "city": "", "voice_comment": "ThoYu specializes in pallet manufacturing equipment. They offer solutions for molded pallets using wood chips, coconut fiber, palm fiber, and waste wood. Two account managers: Sophia Sun and Nancy Wang.", "created_at": "2026-04-17T01:06:49.333832"},
    {"id": 28, "company": "Weihai H&T Tools Co., Ltd", "contact_name": "邓芳媛 Yuan", "phone": "+86-631-5581200, +86-18663131862", "email": "buffmac@126.com", "website": "www.htmaquina.com", "products": "Panel saw, sliding table saw, woodworking machines", "country": "China", "city": "Weihai", "voice_comment": "Компания из Вэйхая, провинция Шаньдун. Контактное лицо Yuan. Производят деревообрабатывающее оборудование, в частности панельные пилы серии MJ6132TZ TY TA под брендом Wood City.", "created_at": "2026-04-17T01:07:22.947756"},
    {"id": 29, "company": "Guangzhou Dade Packing Machinery Co., Ltd", "contact_name": "Serena Chen", "phone": "+8613533933046, 13570287716", "email": "dademachinery@hotmail.com", "website": "www.dademachine.com", "products": "Standard pods making machine (laundry pod production equipment), model DD-5R12-700H, speed 500-1000 pcs/min", "country": "China", "city": "Guangzhou", "voice_comment": "Sales manager Serena Chen, company specializes in pod production machinery, address: Guangdong Guangzhou Baiyun District Xiushui Mulongtan Dade Industrial Park", "created_at": "2026-04-17T01:08:01.118538"},
    {"id": 30, "company": "Luzhou Chengbang Machinery Engineering Co., Ltd", "contact_name": "Yaqi Mou", "phone": "+86 19130086787", "email": "yaqi5258@gmail.com", "website": "http://m.lzcbjx.com/", "products": "Brewing Equipment", "country": "China", "city": "Luzhou", "voice_comment": "Foreign Trade Commissioner. Address: No. 4, Section 2, Taiyang Road, Tai'an Town, Jiangyang District, Luzhou City", "created_at": "2026-04-17T01:08:56.150158"},
    {"id": 31, "company": "Tide Power", "contact_name": "Martin", "phone": "+86 591 2806 8999", "email": "martin@tidepower.uk", "website": "tidepower.uk", "products": "Industrial Hybrid BESS: TP-50BESS, TP-100BESS, TP-200BESS, TP-261BESS", "country": "China", "city": "", "voice_comment": "Sales Manager Martin. WhatsApp: +86 137 6152 8940. Fax: +86 591 2806 8900. Mobile: +86 198 2652 3795. Slogan: Power Solution for Your Better Tomorrow.", "created_at": "2026-04-17T01:09:28.230611"},
    {"id": 32, "company": "Wenzhou Ecotec Energy Equipment Co., Ltd", "contact_name": "Ms. Miya Deng", "phone": "+86 17357796193", "email": "Sales5@ecotecpetroleum.com", "website": "www.ecotecenergy.net", "products": "Gas station equipment, LPG filling skid, processing machinery equipment", "country": "China", "city": "Wenzhou", "voice_comment": "Sales Manager. Tel: +86 577 89893622, Fax: +86 577 89893656. Address: 1406 Digital Mansion Xincheng Avenue, Lucheng District, Wenzhou, Zhejiang, China", "created_at": "2026-04-17T01:10:02.933759"},
    {"id": 33, "company": "VR Star Space", "contact_name": "Jay Cheng, Tanya", "phone": "+86 173 2738 8973, +86 150 6210 0018", "email": "jay@vrstarspace.com, tanya@vrstarspace.com", "website": "www.vrstarspace.com", "products": "VR products", "country": "China", "city": "Xuzhou City, Jiangsu Province", "voice_comment": "Jay Cheng - Senior Sales Assistant, Tanya - Senior Manager. Address: No.33, Times Road, Quanshan Economic Development Zone, Xuzhou City, Jiangsu Province, China, 221000", "created_at": "2026-04-17T01:12:37.547516"},
    {"id": 34, "company": "Dong Guan Feng Rui Electronics Technology Co., Ltd.", "contact_name": "Lorna He", "phone": "+86 135 7450 0302", "email": "lorna@fengruielectronic.com", "website": "www.fengruielectronic.com", "products": "Gaming Headset, Gaming Keyboard, Gaming Mouse, Gaming Accessories, Gaming E-Sports", "country": "China", "city": "Dongguan", "voice_comment": "Foreign Trade Manager. WeChat: koi-Lornahx. QQ: 3504124725. Address: Ma'an Road, Tangjiao Shuiwei Industrial Park, Chashan Town, Dongguan, Guangdong, China, 523000", "created_at": "2026-04-17T01:13:12.829891"},
    {"id": 35, "company": "Shanghai Xianghe Fiber Communication Co.,Ltd / Anhui Xianghe Communication Company (Brand: SHINHO)", "contact_name": "Ada Jiang", "phone": "+86 136 8197 3689", "email": "ada@xhfiber.com", "website": "www.xhfiber.com", "products": "Fiber Fusion Splicer, Optical Test Instruments, Fiber Optic Cleaver, Specialty Fiber Fusion Splicer, Ribbon Fiber Fusion Splicer X-950", "country": "China", "city": "Bengbu, Anhui", "voice_comment": "Sales Director Ada Jiang, also sales1@xhfiber.com, office +86 552 3013522, address: No.621 Gaoxin Road, Bengbu, Anhui, China", "created_at": "2026-04-17T01:13:54.457222"},
    {"id": 36, "company": "LangFang XingTaiLong Communication Material Co.,LTD.", "contact_name": "Lisa Ma", "phone": "+86 155 3168 6369", "email": "sales609@lfxtl.com.cn", "website": "http://www.xtlmedical.com", "products": "Medical devices (wheelchairs and mobility equipment)", "country": "China", "city": "Beiwei, Dacheng County, Hebei", "voice_comment": "SGS certified company, EU-MDR compliant, also listed on Alibaba at xingtailong.en.alibaba.com", "created_at": "2026-04-17T01:14:53.623607"},
    {"id": 37, "company": "Zhejiang Wenxin Mechanical & Electrical Co., Ltd.", "contact_name": "Ellen Yang (杨含笑)", "phone": "+86-152-1475-8900", "email": "ellen@wenxinmfg.com", "website": "www.wenxinmfg.com", "products": "Mechanical & Electrical equipment, Power Sprayers", "country": "China", "city": "Taizhou, Zhejiang Province", "voice_comment": "Sales Manager. Also operates www.power-sprayer.com. Office at No.608-612, Block 1, East, Tengda Centre, No.1800 Donghai Road, Jiaojiang District. Factory at Lvmai South Road, Jiaojiang District.", "created_at": "2026-04-17T01:15:49.659348"},
    {"id": 38, "company": "Jiaxing Tianxu Aviation Technology Co., Ltd.", "contact_name": "Ms. Wei, Ms. Chen", "phone": "+86 18857315898, +86 18858329315", "email": "158036014@qq.com", "website": "www.ietx.com", "products": "T40 Airborne Fire Fighting Water Gun, S200D Airborne Fire Fighting Water Bucket, UAV-mounted firefighting equipment", "country": "China", "city": "Jiaxing", "voice_comment": "Company produces UAV-mounted firefighting equipment including water guns and water buckets for aerial firefighting operations", "created_at": "2026-04-17T01:16:34.756204"},
]


def run_migration():
    conn = sqlite3.connect(DB_PATH)
    count = conn.execute("SELECT COUNT(*) FROM suppliers").fetchone()[0]
    if count > 0:
        print(f"Migration skipped: DB already has {count} records")
        conn.close()
        return

    conn.executemany(
        """INSERT INTO suppliers
           (id, company, contact_name, phone, email, website, products,
            country, city, voice_comment, created_at)
           VALUES (:id, :company, :contact_name, :phone, :email, :website,
                   :products, :country, :city, :voice_comment, :created_at)""",
        HISTORICAL_DATA,
    )
    # Сдвигаем AUTOINCREMENT чтобы новые записи шли после 38
    conn.execute("UPDATE sqlite_sequence SET seq = 38 WHERE name = 'suppliers'")
    conn.commit()
    conn.close()
    print(f"Migration done: inserted {len(HISTORICAL_DATA)} historical suppliers")


if __name__ == "__main__":
    run_migration()
